/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.odontologico;

import Fuentes.fuentes;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author patty
 */
public class RegistroPaciente extends javax.swing.JDialog {

    /**
     * Creates new form RegistroPaciente
     */
    fuentes tipofuentes;
    public RegistroPaciente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();    
        tipofuentes = new fuentes();
        txtNombres.setFont(tipofuentes.fuente(tipofuentes.JOA,0, 30));
        txtApellidos.setFont(tipofuentes.fuente(tipofuentes.JOA,0, 30));
        txtCedula.setFont(tipofuentes.fuente(tipofuentes.JOA,0, 30));
        txtCorElec.setFont(tipofuentes.fuente(tipofuentes.JOA,0, 30));
        jLabel5.setFont(tipofuentes.fuente(tipofuentes.JOA,0, 50));
        txtTelefono.setFont(tipofuentes.fuente(tipofuentes.JOA,0, 30));
        jLabel7.setFont(tipofuentes.fuente(tipofuentes.JOA,0, 30));
        jLabel8.setFont(tipofuentes.fuente(tipofuentes.JOA,0, 30));
        jButton1.setFont(tipofuentes.fuente(tipofuentes.JOA,0, 20));
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel1, "src/Imagenes/paciente.png");
    }
    public void Limpiar(){
        txtNombres.setText("");
        txtApellidos.setText("");
        txtTelefono.setText("");
        txtCorElec.setText("");
        txtCedula.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombres = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JLabel();
        txtCedula = new javax.swing.JLabel();
        txtCorElec = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtTe = new javax.swing.JTextField();
        txtN = new javax.swing.JTextField();
        txtA = new javax.swing.JTextField();
        txtC = new javax.swing.JTextField();
        txtCo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        comboGenero = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombres.setText("Nombres:");
        getContentPane().add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        txtApellidos.setText("Apellidos:");
        getContentPane().add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        txtCedula.setText("Cedula:");
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        txtCorElec.setText("Correo Electronico");
        getContentPane().add(txtCorElec, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        txtTelefono.setText("Telefono:");
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jLabel7.setText("Fecha de nacimiento:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 90, -1));
        getContentPane().add(txtTe, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 140, -1));
        getContentPane().add(txtN, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 140, -1));

        txtA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAActionPerformed(evt);
            }
        });
        getContentPane().add(txtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 140, -1));
        getContentPane().add(txtC, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 140, -1));
        getContentPane().add(txtCo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 140, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 40));

        comboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        getContentPane().add(comboGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 140, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 140, -1));

        jLabel5.setText("Registro Paciente");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 270, 40));

        jLabel8.setText("Genero:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        jPanel1.setBackground(new java.awt.Color(246, 245, 244));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Nombres = txtN.getText();
        String Apellidos = txtA.getText();
        String Correo = txtCo.getText();
        String Telefono = txtTe.getText();
        String Genero = comboGenero.getSelectedItem().toString();
        String Cedula = txtC.getText();
        Date Fecha = jDateChooser1.getDate();
        SimpleDateFormat FechaNacimiento = new SimpleDateFormat("dd/MM/YYYY");
        String FecNac=FechaNacimiento.format(Fecha);
            //Ingreso de datos
            try {//
                BinarioPaciente.crearFilePaciente(new File ("pacientes.dat"));
                BinarioPaciente.agregarPaciente(new Paciente(Nombres, Apellidos, Correo,Telefono,Genero,Cedula,FecNac));
                BinarioPaciente.cerrarArchivo();
                Limpiar();
                JOptionPane.showMessageDialog(this,"¡Éxito!\nSe han ingresado los datos");
            }
            catch (IOException ex){
                JOptionPane.showMessageDialog(this,"No se pueden ingresar los datos","Error",JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistroPaciente dialog = new RegistroPaciente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboGenero;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtA;
    private javax.swing.JLabel txtApellidos;
    private javax.swing.JTextField txtC;
    private javax.swing.JLabel txtCedula;
    private javax.swing.JTextField txtCo;
    private javax.swing.JLabel txtCorElec;
    private javax.swing.JTextField txtN;
    private javax.swing.JLabel txtNombres;
    private javax.swing.JTextField txtTe;
    private javax.swing.JLabel txtTelefono;
    // End of variables declaration//GEN-END:variables
}
